### ISSUE TITLE
Travis not enabled?

### ISSUE THREAD

**Issue by GrahamCampbell** [NoiseByNorthwest/php-spx#102]

**Comment by NoiseByNorthwest** [comment]
The Travis CI integration is fully working. For instance the build status of your PR #101 https://travis-ci.org/NoiseByNorthwest/php-spx/builds/629962713

**Comment by GrahamCampbell** [comment]
Why is there no commit status on GitHub. Does Travis still have access on the third party access control settings? That would stop it pushing status, but allow it to analyze the commits.

**Comment by NoiseByNorthwest** [comment]
Maybe this is related to https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories

But builds are still triggered, there is just no commit-level feedback on github. Do you know if this is however easy to fix ?

**Comment by GrahamCampbell** [comment]
That only affects .com and not .org, I think. All my travis-ci.org builds are working fine with the status API, since the status API has not been deprecated for those kind of integrations, only for "apps". For example:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/2829600/71527585-fdd49780-28d3-11ea-89dd-7d5a19968c27.png">

**Comment by NoiseByNorthwest** [comment]
This is weird, I haven't changed anything and these commit status updates are not working since at least august 2019
![image](https://user-images.githubusercontent.com/1461284/71528133-c9b2a400-28de-11ea-889d-cc8dd90e4e3c.png)

**Comment by GrahamCampbell** [comment]
Kinda odd. What do you see when you visit https://github.com/settings/connections/applications/f244293c729d5066cf27?

**Comment by NoiseByNorthwest** [comment]
![image](https://user-images.githubusercontent.com/1461284/71529580-b0f9bc80-28e5-11ea-8dd7-63168509d3c7.png)

**Comment by GrahamCampbell** [comment]
This is kinda odd. Maybe contact Travis support?
