### ISSUE TITLE
How to scroll down flame graph vertically?

### ISSUE THREAD

**Issue by GrahamCampbell** [NoiseByNorthwest/php-spx#103]
I'm unable to see the deeper calls because there's no way to vertically scroll (as far as I'm aware).

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2829600/71516217-9e5c9480-289f-11ea-9da4-29239d9b07b7.png">

**Comment by GrahamCampbell** [comment]
Related to https://github.com/NoiseByNorthwest/php-spx/issues/100.

**Comment by NoiseByNorthwest** [comment]
Indeed, in your case the Flamegraph UX is terrible. I'll fix #100 soon so that you can tell me if it is enough to mitigate this issue.

**Comment by GrahamCampbell** [comment]
What I did for now was zoom the page out and use an adblocker to remove the bottom. It still struggles with some super nested stuff though:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/2829600/71520256-05d00f80-28b3-11ea-8a85-c6723c9ab230.png">

Maybe we should add more options to the depth limiter config? Like, the UI only goes up to 9, but maybe 25 would be more suitable for some of my code.

**Comment by NoiseByNorthwest** [comment]
On your last screenshot this is not the Flamegraph view but the timeline view. And you can change the depth range of the timeline view by simply dragging with the left click.

**Comment by GrahamCampbell** [comment]
Ah, yes! Thanks. :P

**Comment by NoiseByNorthwest** [comment]
@GrahamCampbell Since the merging of #104 it is now possible to adjust the layout (i.e. the size of timeline, flat profile & Flamegraph widgets) via 2 layout splitters.

![image](https://user-images.githubusercontent.com/1461284/71561038-8177bb00-2a71-11ea-9f1c-8d7901071871.png)

**Comment by GrahamCampbell** [comment]
🚀
