### ISSUE TITLE
Enable/disable at runtime

### ISSUE THREAD

**Issue by GrahamCampbell** [NoiseByNorthwest/php-spx#107]
Is it possible to have a function that can be called at runtime to enable or disable the profiler? This would be useful for profiling things like the Laravel queue worker, which runs for a long time. I would imagine calling start_profiling() and stop_profiling() before starting a job, and after completing it.

**Comment by GrahamCampbell** [comment]
Kinda similar to https://github.com/NoiseByNorthwest/php-spx/issues/44, but easier, since there is no requirement for a process to respond to signals.

**Comment by NoiseByNorthwest** [comment]
I agree, the long living process use cases really need this kind of support. I'm working on it.
