### ISSUE TITLE
http_ip_whitelist does not support IPv6 addresses

### ISSUE THREAD

**Issue by jleroy** [NoiseByNorthwest/php-spx#108]
The offending line is: 

https://github.com/NoiseByNorthwest/php-spx/blob/d05124c4b919130606251b51147aec574cc7af86/src/php_spx.c#L373

`SPX_UTILS_TOKENIZE_STRING` is called with a hardcoded 32 bit size.

**Comment by NoiseByNorthwest** [comment]
Yes this is an undocumented limitation. The 32 number here corresponds to the string representation's length of the address. It can be increased to an oversized 64 chars.

**Comment by jleroy** [comment]
Thank you!
