### ISSUE TITLE
PHP-FPM: Please document the need to enable process.dumpable

### ISSUE THREAD

**Issue by jleroy** [NoiseByNorthwest/php-spx#109]
On most configurations, the PHP-FPM master process runs as root when child processes runs as another unprivileged user.
When this is the case, the line `process.dumpable = yes` must be added to the FPM pool so the `spx_resource_stats_init` function can access `/proc/self/task/XXXX/io` in order to retrieve IO stats. 

This is only required when one of the following metrics is enabled:
 - io
 - ior
 - iow

Although this is more a PHP-FPM configuration issue than an SPX issue, I think mentioning it in the README can save a lot of time to a lot of people.

**Comment by NoiseByNorthwest** [comment]
Related to https://github.com/NoiseByNorthwest/php-spx/issues/89

**Comment by NoiseByNorthwest** [comment]
@jleroy could you take a look at #112 ? I dont know why but I cannot assign it to you.

**Comment by GrahamCampbell** [comment]
> I dont know why but I cannot assign it to you.

Non-members cannot be assigned to issues on GitHub. ;)

**Comment by jleroy** [comment]
@NoiseByNorthwest Sorry for the delay. Done.

**Comment by NoiseByNorthwest** [comment]
> @NoiseByNorthwest Sorry for the delay. Done.

Thanks! And don't worry I wasn't expecting a short delay, I was just wondering if you were properly notified.
