### ISSUE TITLE
SPX Fatal error

### ISSUE THREAD

**Issue by kandy** [NoiseByNorthwest/php-spx#116]
When I try to profile same page multiple times I get
WARNING: [pool www] child 131 said into stderr: "SPX Fatal error at /usr/src/php/ext/spx/src/spx_profiler_tracer.c:289 - Cannot rewind below 0 depth"

**Comment by NoiseByNorthwest** [comment]
Can you give me more details please ? Distro, PHP version or a Dockerfile, the SPX setup and the profiling configuration (especially is sampling is enabled ?).

**Comment by kandy** [comment]
I use docker image php:7.3-fpm-alpine with sampling.
If sampling is disabled than all works good

**Comment by NoiseByNorthwest** [comment]
I'm reproducing it.

**Comment by NoiseByNorthwest** [comment]
@kandy Fixed by #119, can you test with the [fix_116_fatal_error_with_sampling](https://github.com/NoiseByNorthwest/php-spx/tree/fix_116_fatal_error_with_sampling) branch ?

**Comment by kandy** [comment]
@NoiseByNorthwest I can conform that it is fix issue with sampling.  
But  I cannot open result profile in browser. It looks similar to #118
