### ISSUE TITLE
feature: Add possibility to copy from the timeline 

### ISSUE THREAD

**Issue by ilnytskyi** [NoiseByNorthwest/php-spx#124]
There would be nice to have possibility to copy a function name from the timeline view.
I checked the code in `widget.js`

The following logic would work on right click
```
        $(this.viewPort.node).contextmenu(e => {
            if (callIdx == null) {
                return;
            }

            const call = this.profileData.getCall(callIdx);
            let functionName = call.getFunctionName();
            let tmpEl = document.createElement('input');
            tmpEl.value = functionName;

            document.body.appendChild(tmpEl);
            tmpEl.select();
            document.execCommand('Copy');
            document.body.removeChild(tmpEl);

            console.log('Copied:', functionName);
        });
```
What way would be the best way to implement it?

**Comment by NoiseByNorthwest** [comment]
It looks good. But we need a call-to-action or a feedback to confirm the copy to clipboard, but I prefer by far a CTA.
It could be either a button with &#x2398; as label before each function name or a context-menu entry.

The button right after the function name seems to be the more obvious/appealing option but I think it would make the timeline a bit weird.

On the other hand, the custom context-menu option would allow to add more features later (like a highlighting of other calls of the same function).

What do you think ?

**Comment by ilnytskyi** [comment]
@NoiseByNorthwest I think the best one to add a custom context-menu. 
Or for now by single click to fix bottom panel and skip mouseover events to copy from there. But may require to change code in many other events

**Comment by NoiseByNorthwest** [comment]
I think it's a good idea to have the information area fixed on a single click over the function call, as long as any click outside of it would close it.

**Comment by NoiseByNorthwest** [comment]
@ilnytskyi are on you on it ? I can do it if you want.

**Comment by ilnytskyi** [comment]
@NoiseByNorthwest 
I leave it for you :)

I tried to implement fixed info area. 

I added new event on click to add a flag.
```
        $(this.viewPort.node).on('click',e => {
            this.infoViewPort.fixed = true;
        });
```
then modified mousemove event
```
        $(this.viewPort.node).on('mousemove mouseout', e => {
            if (this.infoViewPort == null || this.infoViewPort.fixed === true) {
                return;
            }
```
and `clear` method on object `ViewPort.clear`

```
    clear() {
        if (this.fixed) {
            return;
        }

        this.node.innerHTML = null;
    }
```
I is kind of work. But I faced some problem with selecting text from InfoView fixed svg and prevent dragging event on timeline.

**Comment by NoiseByNorthwest** [comment]
Thanks, I will start from these changes.

**Comment by NoiseByNorthwest** [comment]
The call info are now fixed with a click. This was made by #126 & #127.

The click event was too much conflicting with the drag handling. I've chosen  to handle the click as a "zero" dragging (i.e. drag to initial position) instead.

The only remaining thing to implement is the ability to select the text, but the current design makes it a bit hard.

**Comment by NoiseByNorthwest** [comment]
@ilnytskyi Fixed by #128, can you test with the `call_info_selectable branch` ?

**Comment by ilnytskyi** [comment]
@NoiseByNorthwest 
Yes. I tested it, on `call_info_selectable`  seems to work well 
![Selection_190](https://user-images.githubusercontent.com/3192770/79201673-b9481a00-7e38-11ea-90b2-e9f4112a728b.png)

**Comment by DanielRuf** [comment]
Not sure if this does not work in current Edge versions or if it was removed again.

**Comment by NoiseByNorthwest** [comment]
@DanielRuf I just tested it an c/p is working with SPX@master and both Firefox & Chromium

**Comment by DanielRuf** [comment]
Thanks for verifying @NoiseByNorthwest.

I tested again and it works now. Not sure what I did wrong or if there was some other issue related to my browser extensions or Docker setup (which works now). Only the list of called functions has some problems, but that is a separate issue.
