### ISSUE TITLE
Compilation on mac

### ISSUE THREAD

**Issue by JoyceBabu** [NoiseByNorthwest/php-spx#130]
Compilation of OSX was failing with error

```
checking for zlib header... configure: error: Cannot find zlib.h
```

XCode CLI Tools install SDK at `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk` (Identified by running `xcrun --show-sdk-path`). But the current `config.m4` only searches at `/usr/local` and `/usr`.

**Comment by JoyceBabu** [comment]
I just noticed the environment variable `SPX_ZLIB_INCDIR`.

**Comment by NoiseByNorthwest** [comment]
Where is your zlib.h file located ? If it is a quite common directory I can add it.

**Comment by JoyceBabu** [comment]
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk` contains the SDK for the current version of the operating system.

**Comment by NoiseByNorthwest** [comment]
Ok thanks, so it is an IDE specific path.
I'll however probably improve the zlib dependency handling, as it is done is other extensions.

**Comment by JoyceBabu** [comment]
XCode is the default IDE / build tools by Apple for OSX.

**Comment by BramEsposito** [comment]
If anyone else is trying to compile on macOS (intel): this worked for me: 

`./configure --with-zlib-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/`

thanks for this extension @NoiseByNorthwest ! It looks very promising!
