### ISSUE TITLE
feature request: spx.autostart=on

### ISSUE THREAD

**Issue by duhon** [NoiseByNorthwest/php-spx#136]
It would be nice to get a simple option that will enable the tracking of all requests. Like how it's done in xdebug (xdebug.remote_autostart = on)
At the moment, for http requests, I need to set cookies or an argument, but not all web requests can send cookies, for example, some ajax requests do not transmit cookies. To enable tracking of all requests, I have to change the application code

**Comment by NoiseByNorthwest** [comment]
What I could do is simply to allow to define all available parameters within the INI file:

```ini
spx.parameter.enabled=1
spx.parameter.builtins=1
spx.parameter.sampling_period=50
```

Of course the INI level parameters would have the lowest precedence among all parameter sources which also include the cookies, headers & query parameters.

**Comment by NoiseByNorthwest** [comment]
There is an available implemtation of this feature on [config_level_parameters](https://github.com/NoiseByNorthwest/php-spx/tree/config_level_parameters) branch.

You just have to add the following line in your INI file in order to enable SPX on every request
```ini
spx.http_profiling_enabled=1
```

I cannot merge this branch yet, I need to add some tests.

**Comment by josefsabl** [comment]
I am sorry, but this option seems to do nothing. I would also love the feature to just enable the profiling for every request. At the time I am having trouble profiling SPA application with API PHP backend. When I call the API manually through browser, the request is getting profiled however when Ajax requests the API endpoint, the request doesn't get profiled.
