### ISSUE TITLE
Failed load /js/math.js

### ISSUE THREAD

**Issue by Miteugene** [NoiseByNorthwest/php-spx#140]
There was a problem getting the file math.js

The rest of the files are returned successfully:
/debug/spx/?SPX_UI_URI=/css/main.css    - status 200
/debug/spx/?SPX_UI_URI=/js/dataTable.js - status 200
/debug/spx/?SPX_UI_URI=/js/utils.js          - status 200
/debug/spx/?SPX_UI_URI=/js/fmt.js           - status 200

math.js
/debug/spx/?SPX_UI_URI=/js/math.js         - status 504

I configured spx profiler in docker container and it works well. But if I deploy this container in the google cloud, I get this error with math.js
**Most interesting: if I minify the math.js file, it returns successfully.**

I tried to trace the call stack in the cloud. When requesting math.js file, the call stack is the same as with other files.
...
http_ui_handler_output_file - /usr/share/misc/php-spx/assets/web-ui/js/math.js
read_stream_content
http_ui_handler_shutdown
spx_php_execution_shutdown
reset_context
http_ui_handler_shutdown
spx_php_global_hooks_unset
source_data_to_config
check_access
profiling_handler_init
profiling_handler_ex_set_context
spx_php_global_hooks_set
profiling_handler_ex_set_context
spx_php_execution_init
profiling_handler_ex_set_context
profiling_handler_init
profiling_handler_start
spx_profiler_tracer_create
profiling_handler_ex_hook_before
profiling_handler_ex_hook_before
Some function
profiling_handler_ex_hook_before
profiling_handler_ex_hook_before
profiling_handler_ex_hook_before
profiling_handler_ex_hook_after
profiling_handler_ex_hook_before
Some function
.
.
.
.
profiling_handler_ex_hook_after
profiling_handler_ex_hook_before
profiling_handler_ex_hook_before
Some LAST function
profiling_handler_ex_hook_before - context.profiling_handler.depth++;
profiling_handler_ex_hook_before - end

What could be the problem?

**Comment by keywinf** [comment]
Hi there, 

That's a great repo. Thanks, one of those which make you smile. 

But I encountered a similar problem with /data/metrics/x (x being "metadata" or "get"), with a 404 http code at the end. And it was with Docker Swarm in production (not docker-compose in our local dev computers).

I think there's something around with cloudy stuff.

Anyway, just posting this comment in case the author finds out what may be the cause. But I'll open a dedicated issue if needed.

**Comment by NoiseByNorthwest** [comment]
As expected nothing specific is done regarding math.js, it is just served as a text file.

This file is furthermore quite small when compared to, say, widget.js. So I definitely don't understand why your google cloud gateway reaches its timeout with this particular file.

**Comment by Miteugene** [comment]
Found a solution to this problem:
https://stackoverflow.com/questions/63251335/google-cloud-run-website-timeouts-when-content-length-is-between-4013-8092-chara
