### ISSUE TITLE
Partial access to SPX control panel if index.php does not exist

### ISSUE THREAD

**Issue by 8ctopus** [NoiseByNorthwest/php-spx#145]
Hello Sylvain!

First of all congratulations for creating such a great tool! I've discovered it a few days ago and started eagerly looking into it.
During the tests, I got stuck for quite some time, with a partially loading SPX Control Panel and couldn't figure out why:

![2020-11-04_163848](https://user-images.githubusercontent.com/13252042/98107352-3c57bd00-1ebc-11eb-9162-61d8b62f0f7e.png)
![2020-11-04_163926](https://user-images.githubusercontent.com/13252042/98107421-56919b00-1ebc-11eb-9b03-ecb379dd01df.png)
![2020-11-04_163935](https://user-images.githubusercontent.com/13252042/98107438-58f3f500-1ebc-11eb-8259-08529f67f95f.png)

Finally, I figured out that the problem was the lack of index.php in the directory. A soon as I added index.php everything was back to normal.

I've created a small docker alpine based image that accurately reproduces the problem:
[https://github.com/8ctopus/php-spx-alpine](https://github.com/8ctopus/php-spx-alpine)

```bash
git clone https://github.com/8ctopus/php-spx-alpine

cd php-spx-alpine

docker-compose up
```

open `http://localhost/phpinfo.php?SPX_KEY=dev&SPX_UI_URI=/` and it works!

```bash
mv src/public/index.php src/public/_index.php
```

open `http://localhost/phpinfo.php?SPX_KEY=dev&SPX_UI_URI=/` it stopped working...

Is there an elegant way to avoid the issue? If not, Isuggest to update this part of the readme:

```txt
N.B.: I assume http://localhost/ is served by a PHP script through standard web server feature like directory index or URL rewriting. If this is not the case you can also explicitly point to an existing PHP script as in the following example: http://localhost/my_application.php?SPX_KEY=dev&SPX_UI_URI=/. The PHP script will not be executed, SPX will intercept and disable its execution to serve its content in place.
```

**Comment by NoiseByNorthwest** [comment]
Hi,

You are perfectly right, it does not work without a PHP script configured as a directory index. And BTW thanks for having provided a Docker-based setup.

There is AFAIK no easy way to fix, so I have to update the README consequently.

**Comment by 8ctopus** [comment]
thank you for your response, I've made a pull request, I hope it will be satisfactory #147

**Comment by NoiseByNorthwest** [comment]
Thank you for your patch, it's merged.
