### ISSUE TITLE
[Feature Request] Tying spx_profiler_start to full report result

### ISSUE THREAD

**Issue by dochne** [NoiseByNorthwest/php-spx#153]
In the application I'm attempting to profile, we have a CLI TaskRunner that processes through many different tasks.

In order to get a decent overview, I'm currently using `spx_profiler_start` + `spx_profiler_end` with reporting set as `full` to surround the running of the each task and get indepth logging information.

Ideally, I would like to tie this back to the logs we have about each individual task, but as it stands (as far as I can see) there's no easy link between the finishing of a profiler run and the file it has written into the data_dir (aside from polling the directory itself, which isn't particularly nice)

Would you be opposed to a PR that updated `spx_profiler_stop` to return something like `spx-full-20210112_123649-453f6517b74b-240-511111621` if it did write a log file or null if it did not?

Regardless, I really like the quality of the profiling provided by this repo, thank you! Specifically the lack of proper callstack handling in xhprof has always made me very sad.

**Comment by NoiseByNorthwest** [comment]
I've also considered adding the possibility to add tags in order to help to identify / classify reports with custom metadata (see #125).

**Comment by NoiseByNorthwest** [comment]
However I like your proposition as it looks easy to implement and allows to quickly jump from your log viewer to the analysis screen  of the related report.

**Comment by dochne** [comment]
This is fantastic, thank you! It should allow me to delete the worlds most disgusting `scandir` hack! :D
