### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by ludo9159** [NoiseByNorthwest/php-spx#156]
Are you planning to support Linux (Debian) ARM64 architectures?

**Comment by NoiseByNorthwest** [comment]
If you know how to configure the https://github.com/NoiseByNorthwest/php-spx/blob/master/.travis.yml to target arm64 in addition to x64 I could try to add this support. I expect it to be quite easy to implement as long as I'm able to build & run it on arm64.

**Comment by NoiseByNorthwest** [comment]
It should have been closed by #160
