### ISSUE TITLE
Add a link to Buy a Coffee or similar

### ISSUE THREAD

**Issue by dochne** [NoiseByNorthwest/php-spx#167]
It's a super useful tool, I'd like it if it was possible to send some kind of monetary "thanks" instead of just words.

**Comment by NoiseByNorthwest** [comment]
> It's a super useful tool

Thanks for this feedback! I'm happy to know that it helps you.

> I'd like it if it was possible to send some kind of monetary "thanks" instead of just words.

I appreciate your willingness to give a little more than words :)
I will setup a buymeacoffee account & put the link in the README soon, you'll get noticed here.
