### ISSUE TITLE
[Web UI] Allow removing profiles

### ISSUE THREAD

**Issue by ruudk** [NoiseByNorthwest/php-spx#172]
It would be great if there was a delete button for every profile to quickly delete it.

When doing a lot of profiles, it often becomes a mess.

For now I manually delete the files from `/tmp/spx` but sometimes I remove the wrong profile.

**Comment by BafS** [comment]
Why did you close this issue? It's still relevant IMO

**Comment by ruudk** [comment]
Sure, but feel free to create your own issue. Don't use SPX anymore so don't want this in my list of issues.
