### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by 1ed** [NoiseByNorthwest/php-spx#174]
The latest 0.4.10 release is not compiling in debian because of this error

```
/tmp/src/tmp.aOUy2lu69e/php-spx-0.4.10/src/spx_resource_stats-linux.c:118:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     for (size_t i = 0; i < sizeof(context.lg_buf); i++) {
     ^
/tmp/src/tmp.aOUy2lu69e/php-spx-0.4.10/src/spx_resource_stats-linux.c:118:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
```
It was fixed in https://github.com/NoiseByNorthwest/php-spx/pull/146 but there was no new release since then.

Could you please tag a new release?

**Comment by NoiseByNorthwest** [comment]
I've just tagged master to v0.4.11

**Comment by NoiseByNorthwest** [comment]
release/latest branch is also up to date.

**Comment by 1ed** [comment]
Did you forget to push the tag?

**Comment by NoiseByNorthwest** [comment]
> Did you forget to push the tag?

Yes, sorry, it's fixed now.
