### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by ruudk** [NoiseByNorthwest/php-spx#180]
This makes it easier to add newer PHP versions like PHP 8.1 and 8.2 (dev).

**Comment by NoiseByNorthwest** [comment]
I'm not familiar with GitHub Actions. Could you elaborate a bit what would be the benefits and the required amount of work ?

**Comment by ruudk** [comment]
Create a file in this repository called `.github/workflows/build-and-test.yml` and copy the contents of this example:
https://github.com/php-memcached-dev/php-memcached/blob/master/.github/workflows/build-and-test.yml

Then modify it according to your needs, like Travis.

Commit it to main, and GitHub will automatically run it :) 

Then drop Travis

**Comment by AlexNDRmac** [comment]
@NoiseByNorthwest I've created github actions build workflow. Could you please take a [look](https://github.com/AlexNDRmac/php-spx/actions/runs/2116643013). What do you think about moving from Travis to GA? Also I can add Release publishing action, nightly builds for newest php version, etc...

**Comment by NoiseByNorthwest** [comment]
@AlexNDRmac Thanks, it looks good ! I'm ok to move to GA, but could you also remove the Travis file and update the build status badge in the README ?

> Also I can add Release publishing action, nightly builds for newest php version, etc..

I prefer that we discuss this in another issue so that this one will only cover the Travis -> GA migration.

**Comment by AlexNDRmac** [comment]
@NoiseByNorthwest I'd like to add more features (automation features) with GA and then open PR.
What I mean:
- Cross-platform builds (now extension builds on mac/linux... but I'm sure it's not a big problem to add win support)
- Releases action (You will able to push tag and then Release will be published auto magically... with all compiled ext for all OS and arch and release notes from the changelog)
- Nightly builds with new PHP version to check what needs to be fixed or resolved
- Code Coverage for C code (it should be and I think I can help with it)
- Valgrind checks for memory leaks
- Optionally - some performance tests (it would be great...)

So, I'll prepare part of these features and will send PR.

**Comment by NoiseByNorthwest** [comment]
I'm OK with all of these points, and the win support would be a great enhancement !

**Comment by NoiseByNorthwest** [comment]
Implemented by #190
