### ISSUE TITLE
Doc: Clarify what `Inc.` and `Exc.` mean in the table

### ISSUE THREAD

**Issue by LordSimal** [NoiseByNorthwest/php-spx#193]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/9105243/181498523-5c3bda7b-ef06-4cea-aa11-1bfda695654f.png">

I was not able to find a documentation which explains the difference between `Inc.` and `Exc.`

This run was generated without profiling internal PHP methods, therefore it can't really be "including/exlcuding internal functions"

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/9105243/181498626-87da0035-f528-45ac-8f63-7637c53f04e2.png">

**Comment by LordSimal** [comment]
My guess would be the difference between:

- including called functions (aka "sub-calls") and their time spent and
- excluding called functions

But is that correct? Can we maybe add a simple example to the doc which ilustrates this?

**Comment by NoiseByNorthwest** [comment]
That is correct.
