### ISSUE TITLE
PHP 5.4 support

### ISSUE THREAD

**Issue by Athorcis** [NoiseByNorthwest/php-spx#226]
I know that PHP 5.4 is not used by a lot of people nowadays and that I should probably migrate to a newer version, but would accept a PR that adds PHP 5.4 compatibility?

**Comment by NoiseByNorthwest** [comment]
As long as it does not impact other versions I do not see any reason to reject such PR. I'm just surprised to have a contribution adding the support for a PHP version whose EOL date has been reached 8 years ago.

Keep also in mind that in the future PHP5 support may be dropped.
