### ISSUE TITLE
Potential misinformation about leak

### ISSUE THREAD

**Issue by oleg-andreyev** [NoiseByNorthwest/php-spx#231]
https://github.com/php/php-src/issues/12508

![image](https://github.com/NoiseByNorthwest/php-spx/assets/1244112/656c890f-0048-4e8c-aecd-8f4779a2af1a)

Allocated count 2M, free count 1M
Allocated bytes vs Free bytes

**Comment by NoiseByNorthwest** [comment]
As explained here https://github.com/php/php-src/issues/12508 the observed behavior looks OK to me.

**Comment by NoiseByNorthwest** [comment]
@oleg-andreyev is everything clear for you ? Can it be closed ?

**Comment by oleg-andreyev** [comment]
Yes 👍 thanks
