### ISSUE TITLE
ESM modules resolution error

### ISSUE THREAD

**Issue by Athorcis** [NoiseByNorthwest/php-spx#233]
Hello,

When loading SPX on a server without URL rewriting and thus having a php file inside a URL, the UI won't load because some of the JS files fail to load. The files that won't load are the ones that are imported inside ESM modules, the reason is : the different algorithms used for resolution, on script tags, relative paths are relative to the current page (which includes the filename) but inside an ESM module, relative paths are relative to current file directory (but since there is no rewriting, no PHP script is loaded and the js does not load)

Would you accept a PR that replaces current import directives with dynamic import ?

<img width="1398" alt="image" src="https://github.com/NoiseByNorthwest/php-spx/assets/4405110/9c285dbc-b1bd-42d0-8ef5-34d7353fec15">

<img width="687" alt="image" src="https://github.com/NoiseByNorthwest/php-spx/assets/4405110/1b9b9069-c781-4330-a442-777992cb211b">

**Comment by NoiseByNorthwest** [comment]
It sounds like an improvement without downsides, so I'm OK.
