### ISSUE TITLE
Install fails in MacOS Ventura

### ISSUE THREAD

**Issue by mtangoo** [NoiseByNorthwest/php-spx#236]
OS: MacOS Ventura
Package Manager: Homebrew
PHP Version: 
PHP 8.2.12 (cli) (built: Nov  5 2023 21:48:15) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.12, Copyright (c), by Zend Technologies

I built it fine but trying to install I get error message:
```
mkdir: /usr/local/Cellar/php/8.2.12_1/pecl: File exists
mkdir: /usr/local/Cellar/php/8.2.12_1/pecl: No such file or directory
make: *** [install-modules] Error 1
```

contents of the path in complain:
```
 /usr/local/Cellar/php/8.2.12_1$ ls -lF
total 160
-rw-r--r--@  1 user  admin   9588 Nov 21 17:31 INSTALL_RECEIPT.json
-rw-r--r--@  1 user  admin   3204 Oct 24 22:22 LICENSE
-rw-r--r--@  1 user  admin  48531 Oct 24 22:22 NEWS
-rw-r--r--@  1 user  admin   5074 Oct 24 22:22 README.md
drwxr-xr-x@ 12 user  admin    384 Nov 21 17:31 bin/
-rw-r--r--@  1 user  admin    772 Nov 21 17:31 homebrew.mxcl.php.plist
-rw-r--r--@  1 user  admin    263 Nov 21 17:31 homebrew.php.service
drwxr-xr-x@  3 user  admin     96 Oct 24 22:22 include/
drwxr-xr-x@  4 user  admin    128 Oct 24 22:22 lib/
lrwxr-xr-x@  1 user  admin     23 Nov 21 17:31 pecl@ -> /usr/local/lib/php/pecl
drwxr-xr-x@  3 user  admin     96 Oct 24 22:22 sbin/
drwxr-xr-x@  4 user  admin    128 Oct 24 22:22 share/
```

What am I doing wrong?

**Comment by NoiseByNorthwest** [comment]
Could you please past the full log of typed commands and their output ?

**Comment by mtangoo** [comment]
I did brew upgrade and now it is running at PHP8.3 which is not supported by the tool. Not sure if it will be easy to force it build or something, or I have to wait for the support for 8.3

**Comment by NoiseByNorthwest** [comment]
`master` branch does support PHP8.3. Skip the `git checkout release/latest` and it will be fine.

```shell
git clone https://github.com/NoiseByNorthwest/php-spx.git
cd php-spx
phpize
./configure
make
sudo make install
```

**Comment by mtangoo** [comment]
> `master` branch does support PHP8.3. Skip the `git checkout release/latest` and it will be fine.

It works fine and installs with master branch and PHP8.3. Thanks for support!
Closing the issue!
