### ISSUE TITLE
configure error on macOS : cannot find zlib

### ISSUE THREAD

**Issue by xpech** [NoiseByNorthwest/php-spx#238]
Configure is not able to find zlib.h on macOS.

Adding   /opt/local  on config.m4 line 43 resolve the issue. 

I'm not allowed top send you a branch or PR.

Hope this helps,

<img width="637" alt="Capture d’écran 2024-01-09 à 13 15 27" src="https://github.com/NoiseByNorthwest/php-spx/assets/4090829/f297c792-4d1e-4050-9224-9b4bf57402ac">

**Comment by Moskito89** [comment]
If you are using Homebrew, you can run `./configure --with-zlib-dir=/opt/homebrew/opt/zlib` too.

**Comment by NoiseByNorthwest** [comment]
Would it be relevant to make config.m4 handle `/opt/local` as in @xpech 's screenshot ?

**Comment by xpech** [comment]
There is two package manager under macOS, Homebrew and Macport. For Macport user adding this search path fix the lib search issue.  Using --with-zlib-dir not working.
The fix broke nothing else.
