### ISSUE TITLE
Not able to see traces

### ISSUE THREAD

**Issue by IgalSc** [NoiseByNorthwest/php-spx#247]
I followed the installation instructions, 
installed dev php package `sudo apt-get install php5.6-dev`, then `sudo apt-get install zlib1g-dev`, then `git clone https://github.com/NoiseByNorthwest/php-spx.git
cd php-spx
git checkout release/latest
phpize
./configure
make
sudo make install`

afterwards I added the following to /etc/php/5.6/cli/php.ini and /etc/php/5.6/apache2/php.in

`extension=spx.so
spx.http_enabled=1
spx.http_profiling_enabled=1
spx.http_key="the_key_here"
spx.http_ip_whitelist="*"`

and restarted apache

when I access the https://webserver_uri/api/?SPX_KEY=the_key_here&SPX_UI_URI=/ i see the control panel GUI
However, I'm willing to analyze the live traffic, that go the webserver_uri/api/ endpoint, similar to:

GET /api/get_order_details

I'm only seeing the control panel
is there a way to have the live traffic being profiled?

**Comment by NoiseByNorthwest** [comment]
Only "your traffic" (i.e. any HTTP requests with profiling enabled via cookies/query params). When you enable profiling from the web UI, it is only enabled for your current browser session via a set of cookies which will be added to every HTTP requests sent to  the current domain.

**Comment by IgalSc** [comment]
I see
Thank you!
