### ISSUE TITLE
/_spx/data/reports/metadata not picking up generated reports.

### ISSUE THREAD

**Issue by BarryHelfrich** [NoiseByNorthwest/php-spx#25]
I have set the following config file:
extension=spx.so
spx.data_dir = /srv/nginx/profiler
spx.http_enabled = 1
spx.http_key = XXXXX
spx.http_ip_whitelist="127.0.0.1,XX.XX.XX.XX"

I enable profiling from the web ui and refresh a page im profiling - it clearly takes time and is doing its thing. The profiles are being written to the configured directory eg:

spx-full-20180314_115412-xxx-14281-1804289383.json
spx-full-20180314_115412-xxx-14281-1804289383.txt.gz

However the endpoint /_spx/data/reports/metadata does not serve the reports to the web ui so nothing populates and I cant select the profile to view.

I am running php-fpm on nginx on centos 7.4.1708.
PHP version: PHP 7.1.15

Let me know if I can get you any other data to help debug.

**Comment by BarryHelfrich** [comment]
I am also getting these errors firing in nginx error.log

2018/03/14 12:36:34 [error] 14075#14075: *5579 FastCGI sent in stderr: "PHP message: PHP Notice:  spx: access granted: "XX.XX.XX.XX" IP with "XXX" key in Unknown on line 0" while reading response header from upstream, client: XX.XX.XX.XX, server: , request: "GET /_spx/data/reports/metadata HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "XX.XX.XX"

**Comment by BarryHelfrich** [comment]
I am aslo getting these errors firing in nginx error.log:

2018/03/14 12:36:34 [error] 14075#14075: *5579 FastCGI sent in stderr: "PHP message: PHP Notice:  spx: access granted: "XX.XX.XX.XX" IP with "XXX" key in Unknown on line 0" while reading response header from upstream, client: XX.XX.XX.XX, server: , request: "GET /_spx/data/reports/metadata HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "XX.XX.XX"

**Comment by NoiseByNorthwest** [comment]
Thanks for this detailed issue.

Can you also, in your browser debug panel, copy the /_spx/data/reports/metadata url as curl command, add '-i' option to the command (to show response headers) and then run and paste the output here ?

**Comment by BarryHelfrich** [comment]
Hello, thanks for the quick reply.
Request Headers (/_spx/data/reports/metadata):
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Authorization: Basic XXXXXXXXXXX
Cache-Control: no-cache
Connection: keep-alive
Cookie: _ga=XXXXX; SPX_KEY=XXXX; SPX_DEPTH=0; SPX_FULL_RES=0; SPX_BUILTINS=0; SPX_METRICS=ct,zo; SPX_ENABLED=1
Developer-Mode: 1
DNT: 1
Host: salience.cashbackapp.com
Pragma: no-cache
Referer: https://xxx.xxx.xxx/_spx/
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
X-Requested-With: XMLHttpRequest

Response headers:
Connection: keep-alive
Content-Type: application/json
Date: Wed, 14 Mar 2018 14:02:47 GMT
Server: nginx
Strict-Transport-Security: max-age=15768000
Transfer-Encoding: chunked

Response body:

{"results": [
]}

Hope this helps, let me know if there is anything else I can do.

**Comment by NoiseByNorthwest** [comment]
This is weird, do you have multiple front ends behind a load balancer ? The metadata endpoint just list `{dataDir}/*.json` files.

**Comment by BarryHelfrich** [comment]
No its a straight request to a development server without any intermediaries. The data dir is populated successfully for every profiling enabled request as well.

Distro is Centos 7.4 and kernal 3.10.0-693.21.1.el7.x86_64

**Comment by NoiseByNorthwest** [comment]
OK thanks, I may add some logs this evening.

**Comment by BarryHelfrich** [comment]
Also worth noting that SELinux is disabled and file permissions are nginx:nginx 644.

**Comment by NoiseByNorthwest** [comment]
I've just push this branch https://github.com/NoiseByNorthwest/php-spx/tree/debug_25 which adds some useful logs.

**Comment by zhanglei** [comment]
![image](https://user-images.githubusercontent.com/241508/37449819-a71b3648-2866-11e8-934b-065992300f08.png)
![image](https://user-images.githubusercontent.com/241508/37449835-bb00d24e-2866-11e8-8d1d-99ebdbec67d9.png)

**Comment by NoiseByNorthwest** [comment]
@zhanglei Thanks! Indeed some readdir implementations do not handle d_type and set it to DT_UNKNOWN in all cases. Anyway, this check is not so relevant and can be removed.

@BarryHelfrich I've push https://github.com/NoiseByNorthwest/php-spx/tree/fix_25 can you try it ?

**Comment by BarryHelfrich** [comment]
Thats fixed it on fix_25 branch. Thanks looks great.

**Comment by NoiseByNorthwest** [comment]
OK nice, merged.
