### ISSUE TITLE
I'll implement this feature as a part of a full rewrite of the web UI.

### ISSUE THREAD

**Issue by Sec32fun32** [NoiseByNorthwest/php-spx#276]
I'll implement this feature as a part of a full rewrite of the web UI.

_Originally posted by @NoiseByNorthwest in https://github.com/NoiseByNorthwest/php-spx/issues/273#issuecomment-2432819622_

**Comment by NoiseByNorthwest** [comment]
@Sec32fun32 closed since it does not match the expected content for an issue or a feature request.
