### ISSUE TITLE
not able to compile

### ISSUE THREAD

**Issue by nasredin** [NoiseByNorthwest/php-spx#6]
hello,

my compilation ends with:
cc1: warnings being treated as errors
/usr/src/php-spx/src/spx_output_stream.c: In function 'gz_file_handler_vprintf':
/usr/src/php-spx/src/spx_output_stream.c:179: error: implicit declaration of function 'gzvprintf'
compilation terminated due to -Wfatal-errors.
make: *** [src/spx_output_stream.lo] Error 1

centos 6
php56w

**Comment by NoiseByNorthwest** [comment]
Hello,

I've created the `remove_gzvprintf_use` branch with the corresponding fix, can you try it ?

**Comment by nasredin** [comment]
wow, it was quick.... 
problem fixed

thx

**Comment by NoiseByNorthwest** [comment]
Thanks for your feedback!
