### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by alexeyshockov** [NoiseByNorthwest/php-spx#7]
Hey, thanks for a cool piece of software. Do you have any plans to support MacOS in future versions?

**Comment by NoiseByNorthwest** [comment]
Hello,

macOS is planned to be the first major platform, other than Linux, to be supported.
I will investigate support for it after the release of the web UI (planned for late October).

**Comment by NoiseByNorthwest** [comment]
Fixed by #13
