### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by nova-powered** [NoiseByNorthwest/php-spx#81]
Hi, thank you for building this awesome extension! Is FreeBSD support planned in the future?

**Comment by NoiseByNorthwest** [comment]
Hi,

I guess most of the complexity is setting up a FreeBSD VM (or having access to a FreeBSD host).
Can you help me in this regard ?

**Comment by NoiseByNorthwest** [comment]
Yes, my github username at gmail dot com (or git clone this repo and check any of my commits in "git log")

**Comment by NoiseByNorthwest** [comment]
@nova-powered do not send me ssh credentials, I will send you my public key (safer for you).

**Comment by Peter2121** [comment]
Any news about FreeBSD support?

**Comment by NoiseByNorthwest** [comment]
Nothing new, I still need a vm or at least a freebsd env for TravisCI.

**Comment by Peter2121** [comment]
OK, I'll try to search for a solution.
AFAIK, TravisCI does not support FreeBSD.

**Comment by Peter2121** [comment]
BTW, do Virtual Box VM files fit your need? Or you absolutely need a hosted solution?

**Comment by NoiseByNorthwest** [comment]
Yes, a ready to use Virtual Box VM is ok.

> AFAIK, TravisCI does not support FreeBSD.

Do you know a free CI service which supports FreeBSD ? Without a CI I cannot guarantee that I will not break the FreeBSD support.
I've the same issue with macOS BTW.

**Comment by Peter2121** [comment]
OK, I'll share a FreeBSD image for you.
As about CI, I use self-hosted Jenkins, it is natively supported on FreeBSD.

**Comment by NoiseByNorthwest** [comment]
@Peter2121 I've just created #161, can you test it ?
