### ISSUE TITLE
Profiling in curl or postman

### ISSUE THREAD

**Issue by idiglove** [NoiseByNorthwest/php-spx#82]
First of all, your app works well and looks awesome.

Although is there any option to profile requests made from curl or postman?

Thanks!

**Comment by NoiseByNorthwest** [comment]
Yes you can profile any URL outside a profiling session, just trigger profiling via query string parameters as in the following example (assuming development configuration [described here](https://github.com/NoiseByNorthwest/php-spx#private-environment)):

```shell
curl 'localhost/?SPX_ENABLED=1&SPX_KEY=dev'
```

**Comment by idiglove** [comment]
Great it works. Thanks
I did this:
`curl 'localhost/{route_here}?SPX_ENABLED=1&SPX_KEY=dev'`

**Comment by NoiseByNorthwest** [comment]
Thanks for your feedback
