### ISSUE TITLE
"access granted" notice

### ISSUE THREAD

**Issue by pilot114** [NoiseByNorthwest/php-spx#88]
https://github.com/NoiseByNorthwest/php-spx/blob/75be219b190ae4b42616dd64a2b3abd9e81eb439/src/php_spx.c#L345

maybe not display it as a notice?
Not very informative and it looks as if something has broken, although it is not.

**Comment by NoiseByNorthwest** [comment]
My first intent was to log something for ease of debugging, and I still think it is useful here to have some info/debug logs. Unfortunately PHP, at its core, does not provide general purpose logging facility.

One thing I may add is a configuration flag to explicitly enable these notice logs, leaving them disabled by default.

**Comment by pilot114** [comment]
Yeah, I think that would be useful.
Usually, developers locally turn on notice output, and it breaks ui, among other things. (sometimes appears  message "headers already sent")

**Comment by NoiseByNorthwest** [comment]
> Usually, developers locally turn on notice output, and it breaks ui, among other things. (sometimes appears message "headers already sent")

SPX handles this case as it does not output logs when `log_errors` is off.

https://github.com/NoiseByNorthwest/php-spx/blob/aa032b744f7820a328225a794699bfd545bb3312/src/spx_php.c#L764
http://php.net/manual/en/errorfunc.configuration.php#ini.log-errors

**Comment by NoiseByNorthwest** [comment]
@pilot114 I've finally just removed the access granted log :)
