### ISSUE TITLE
Fatal problems when setting sampling above 5us

### ISSUE THREAD

**Issue by funkjedi** [NoiseByNorthwest/php-spx#91]
If I try using a sampling rate above 5us SPX causes the world to explode.

```
[17-Nov-2018 23:40:52] WARNING: [pool www] child 18057 said into stderr: "SPX Fatal error at /opt/php-spx/src/spx_profiler_tracer.c:289 - Cannot rewind below 0 depth"
[17-Nov-2018 23:40:52] WARNING: [pool www] child 18057 exited with code 1 after 12.701341 seconds from start
```
https://github.com/NoiseByNorthwest/php-spx/blob/617bba7d606dd120d61df939c3fa8fbaac7c96f9/src/spx_profiler_tracer.c#L288-L290

I realize there's probably not really anything actionable here. This is only happening with one of the PHP apps I'm profiling. Working fine with others I've profiled in the same environment. 

All I'm really looking for is any ideas you may have about where to start looking to try and resolve. For example what kinds of behaviours in a PHP app could trigger this error in SPX.

**Comment by funkjedi** [comment]
K, you can ignore this. Found the source of the problem. There was code searching a Collection of Eloquent models which caused a cascading cacophony of consequence.

**Comment by NoiseByNorthwest** [comment]
This is still unexpected to reach this abortion point, whatever the user code is doing. It may be due to a bug in SPX sampler.
I'm currently rewriting this part to increase performance and I will investigate the cause of this issue.
