### ISSUE TITLE
Failed load JS resource in Safari

### ISSUE THREAD

**Issue by efureev** [NoiseByNorthwest/php-spx#99]
All JS assets not loaded in Safari (Version 13.0.3). Without errors in console.
Just return HTML code of base location `/` of the host.

CSS file - loaded well.
In Chrome (78.0.3904.108) - All ok.

Singly, by the url `http://localhost/?SPX_UI_URI=/js/dataTable.js`, the js files - loaded ok

**Comment by NoiseByNorthwest** [comment]
This is weird. Unfortunately I can't reproduce it as Safari is not available on Linux.
It sounds like the JS import statement does not take into account the query-string part of the URL.
Anyway, I was never expecting the web UI to work on Safari, I can only support Chromium-based & Firefox browsers.
